version: "3.7"

services:
  server:
    container_name: server
    build:
      context: ./server/
      target: development
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: yarn start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
      - client

  client:
    build:
      context: ./client/
      target: development
    command: yarn start
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4201:4201"
    networks:
      - webnet

  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata:
